/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gereestoque;

import DAO.Conexao;
import DAO.FornecedorDAO;
import DAO.ProdutoDAO;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.Fornecedor;

/**
 *
 * @author tamara
 */
public class ConsultaFornecedor extends javax.swing.JFrame {
    Fornecedor f;
    /**
     * Creates new form ConsultaFornecedor
     */
    public ConsultaFornecedor() {
        initComponents();
    }
    public void Limpar(){
        con_nomeFor.setText("");
        con_cnpjFor.setText("");
        con_telFor.setText("");
        con_EndFor.setText("");
        con_emailFor.setText("");
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        busca_for = new javax.swing.JTextField();
        pesq_for = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        con_nomeFor = new javax.swing.JTextField();
        con_cnpjFor = new javax.swing.JTextField();
        con_telFor = new javax.swing.JTextField();
        con_emailFor = new javax.swing.JTextField();
        con_EndFor = new javax.swing.JTextField();
        Con_For = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_cadLimpar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pesq_for.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisa.png"))); // NOI18N
        pesq_for.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pesq_forMouseClicked(evt);
            }
        });
        pesq_for.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesq_forActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Código:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Endereço:");

        con_nomeFor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        con_cnpjFor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        con_telFor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        con_telFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                con_telForActionPerformed(evt);
            }
        });

        con_emailFor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        con_EndFor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        con_EndFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                con_EndForActionPerformed(evt);
            }
        });

        Con_For.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        Con_For.setText("Alterar");
        Con_For.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Con_ForMouseClicked(evt);
            }
        });
        Con_For.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Con_ForActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nome:");

        btn_cadLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/limpar.png"))); // NOI18N
        btn_cadLimpar.setText("Limpar");
        btn_cadLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadLimparActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("CNPJ:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Telefone:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("E-mail:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(busca_for, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pesq_for, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(con_emailFor, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 319, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btn_cadLimpar)
                                        .addGap(18, 18, 18)
                                        .addComponent(Con_For))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(con_nomeFor)
                                            .addComponent(con_EndFor))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(con_telFor, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(con_cnpjFor, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(6, 6, 6)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pesq_for, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(busca_for, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(con_nomeFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(con_cnpjFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(con_EndFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(con_telFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(con_emailFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Con_For)
                    .addComponent(btn_cadLimpar))
                .addGap(89, 89, 89))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pesq_forActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesq_forActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_pesq_forActionPerformed

    private void con_telForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_con_telForActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_con_telForActionPerformed

    private void con_EndForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_con_EndForActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_con_EndForActionPerformed

    private void Con_ForMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Con_ForMouseClicked
        f.nome = this.con_nomeFor.getText();
        f.cnpj = this.con_cnpjFor.getText();
        f.tel = this.con_telFor.getText();
        f.endereco = this.con_EndFor.getText();
        f.email = this.con_emailFor.getText();
        f.id = Integer.parseInt(this.busca_for.getText());
        Conexao connection = Conexao.getInstance();
        String sql = "UPDATE fornecedor SET nome =? ,cnpj =?,tel = ?,endereco = ?, email = ? WHERE id = ? ";
        try {
            PreparedStatement stm = connection.getConnection().prepareStatement(sql);
            stm.setString(1,f.nome);
            stm.setString(2,f.cnpj);
            stm.setString(3,f.tel);
            stm.setString(4,f.endereco);
            stm.setString(5,f.email);
            stm.setInt(6,f.id);
            stm.executeUpdate();
            JOptionPane.showMessageDialog(null, "Alteração realizada");
            
            
        }catch(SQLException e){
            System.out.println("ERRO:"+ e);
        }
        finally {
            connection.destroy();
        } 
        
    }//GEN-LAST:event_Con_ForMouseClicked

    private void Con_ForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Con_ForActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Con_ForActionPerformed

    private void btn_cadLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadLimparActionPerformed
        // TODO add your handling code here:
        this.Limpar();
    }//GEN-LAST:event_btn_cadLimparActionPerformed

    private void pesq_forMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesq_forMouseClicked
        // TODO add your handling code here:
        
        Integer num = Integer.parseInt(busca_for.getText());
        FornecedorDAO dao = new FornecedorDAO();
        this.f = dao.buscaFornecedor(num);
        con_nomeFor.setText(f.nome);
        con_cnpjFor.setText(f.cnpj);
        con_emailFor.setText(f.email);
        con_telFor.setText(f.tel);
        con_EndFor.setText(f.endereco);
    }//GEN-LAST:event_pesq_forMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Con_For;
    private javax.swing.JButton btn_cadLimpar;
    private javax.swing.JTextField busca_for;
    private javax.swing.JTextField con_EndFor;
    private javax.swing.JTextField con_cnpjFor;
    private javax.swing.JTextField con_emailFor;
    private javax.swing.JTextField con_nomeFor;
    private javax.swing.JTextField con_telFor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton pesq_for;
    // End of variables declaration//GEN-END:variables
}
