/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gereestoque;

import Command.Loja;
import Command.PagamentoBoleto;
import Command.PagamentoCartaoCredito;
import Singleton.Conexao;
import DAO.ProdutoDAO;
import DAO.VendasDAO;
import interfaces.IteradorInterface;
import interfaces.PagamentoCommand;
import iterator.ProdutosCompra;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.Venda;

/**
 *
 * @author tamara
 */
public class FinalizarCompra extends javax.swing.JFrame {
    double preco = 0;
    Loja loja = new Loja();
    int b,c;
    ProdutosCompra produtoCompra;
    /**
     * Creates new form FinalizarCompra
     */
    public FinalizarCompra() {
        initComponents();
    }
    public FinalizarCompra(ProdutosCompra pc) {
        initComponents();
       produtoCompra = pc; 
        for (IteradorInterface it = pc.criarIterator(); !it.isDone(); it.next()) {
            preco += it.currentItem().preco;
            
        }
        
        valTotal.setText(String.valueOf(preco));
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        valTotal = new javax.swing.JLabel();
        cartao = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        boleto = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Total Compra:");

        valTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        valTotal.setForeground(new java.awt.Color(255, 0, 51));
        valTotal.setText("00,00");

        cartao.setText("Cartão de Crédto");
        cartao.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cartaoItemStateChanged(evt);
            }
        });
        cartao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartaoMouseClicked(evt);
            }
        });
        cartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartaoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Formas de Pagamento:");

        boleto.setText("Boleto");
        boleto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boletoItemStateChanged(evt);
            }
        });
        boleto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boletoMouseClicked(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Finalizar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boleto)
                        .addGap(18, 18, 18)
                        .addComponent(cartao))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valTotal)))
                .addContainerGap(147, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(valTotal))
                .addGap(41, 41, 41)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boleto)
                    .addComponent(cartao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boletoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boletoItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_boletoItemStateChanged

    private void cartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cartaoActionPerformed

    private void cartaoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cartaoItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cartaoItemStateChanged

    private void boletoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boletoMouseClicked
        // TODO add your handling code here:
        b = 2;
        
    }//GEN-LAST:event_boletoMouseClicked

    private void cartaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartaoMouseClicked
        // TODO add your handling code here:
        b = 1;
    }//GEN-LAST:event_cartaoMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        if (b == 2){
            loja.executarCompra(preco, new PagamentoBoleto());
        }
        if (c == 1){
            loja.executarCompra(preco, (PagamentoCommand) new PagamentoCartaoCredito());
        }
        ProdutoDAO pDAO =new ProdutoDAO();
        VendasDAO  venda = new VendasDAO();
        Venda v = new Venda();
        for (IteradorInterface it = produtoCompra.criarIterator(); !it.isDone(); it.next()) {
            
            pDAO.descontaProduto(it.currentItem().codP);
            
        }
        v.valorTotal = this.preco;
        venda.registrarVendas(v);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalizarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalizarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalizarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalizarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinalizarCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton boleto;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cartao;
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel valTotal;
    // End of variables declaration//GEN-END:variables
}
