/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gereestoque;

import DAO.ProdutoDAO;
import model.Produto;
import iterator.ProdutosCompra;
import javax.swing.JOptionPane;

/**
 *
 * @author tamara
 */
public class ItensVenda extends javax.swing.JFrame {
    ProdutosCompra pc = new ProdutosCompra();

    Produto p;
    private int cod;
    /**
     * Creates new form ItensVenda
     */
    public ItensVenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pesquisar_itemvenda = new javax.swing.JButton();
        pes_ItemVenda = new javax.swing.JTextField();
        con_nome = new javax.swing.JLabel();
        add_p = new javax.swing.JButton();
        fimCompra = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        conNome = new javax.swing.JLabel();
        con_preco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pesquisar_itemvenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisa.png"))); // NOI18N
        pesquisar_itemvenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pesquisar_itemvendaMouseClicked(evt);
            }
        });
        pesquisar_itemvenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisar_itemvendaActionPerformed(evt);
            }
        });

        add_p.setText("Adicionar");
        add_p.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_pMouseClicked(evt);
            }
        });
        add_p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_pActionPerformed(evt);
            }
        });

        fimCompra.setText("Finalizar Compra");
        fimCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fimCompraMouseClicked(evt);
            }
        });
        fimCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fimCompraActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Nome");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Preço");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Código");

        conNome.setText("jLabel4");

        con_preco.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fimCompra)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(con_nome))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel1))
                            .addComponent(conNome, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(con_preco))
                        .addGap(123, 123, 123)
                        .addComponent(add_p))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pes_ItemVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pesquisar_itemvenda)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pes_ItemVenda)
                    .addComponent(pesquisar_itemvenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(9, 9, 9)
                        .addComponent(con_nome))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(conNome)
                            .addComponent(con_preco)
                            .addComponent(add_p))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                .addComponent(fimCompra)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pesquisar_itemvendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisar_itemvendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisar_itemvendaActionPerformed

    private void pesquisar_itemvendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesquisar_itemvendaMouseClicked
        // TODO add your handling code here:
        Integer num = Integer.parseInt(pes_ItemVenda.getText());
        ProdutoDAO dao = new ProdutoDAO();
       this.p = dao.buscaProduto(num);
        con_nome.setText(Integer.toString(p.codP));
        conNome.setText(p.nomeP);
        con_preco.setText(Float.toString(p.preco));
    }//GEN-LAST:event_pesquisar_itemvendaMouseClicked

    private void add_pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_pActionPerformed
        // TODO add your handling code here:
        
     
    }//GEN-LAST:event_add_pActionPerformed

    private void fimCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fimCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fimCompraActionPerformed

    private void fimCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fimCompraMouseClicked
        // TODO add your handling code here:
        FinalizarCompra fim = new FinalizarCompra(pc);
        this.setVisible(false);
        fim.setVisible(true);
        
    }//GEN-LAST:event_fimCompraMouseClicked

    private void add_pMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_pMouseClicked
        // TODO add your handling code here:
         
        if(p.qnt != 0){
           pc.lista.add(p);    
        }
        else {
         JOptionPane.showMessageDialog(null,"Produto em falta!");
        }
        
    }//GEN-LAST:event_add_pMouseClicked
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItensVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItensVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItensVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItensVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItensVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_p;
    private javax.swing.JLabel conNome;
    private javax.swing.JLabel con_nome;
    private javax.swing.JLabel con_preco;
    private javax.swing.JButton fimCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField pes_ItemVenda;
    private javax.swing.JButton pesquisar_itemvenda;
    // End of variables declaration//GEN-END:variables
}
